// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "vueserverlessproject-20181120175242--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d3s558mu75szef.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:31c9bca9-dec2-4af3-9097-a6bf63f2dbd4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qiU8lXkwL",
    "aws_user_pools_web_client_id": "515imgn0qj8nftb8vgi93u64ip"
};


export default awsmobile;
